### ISSUE TITLE
suggest: change color

### ISSUE THREAD

**Issue by sheyhii** [sheyhii/youtube-test#1]
I think it looks better if the main title is a bit more orange.
the styling rule could be changed like this:
```css
h1{
color: #e8c4ab4;
}
```
